spring.application.name=apigateway

spring.data.redis.host=localhost
spring.data.redis.port=6379

rate.limit.max-requests=10
rate.limit.window-size=60000

gateway.routes.posts=https://jsonplaceholder.typicode.com/posts
gateway.routes.users=https://jsonplaceholder.typicode.com/users
gateway.routes.comments=https://jsonplaceholder.typicode.com/comments